theme: minima

![Cover pic](/assets/DSC01032.JPG)

title: LIFE-TRAVEL-PHOTOGRAPHY
author: Sherry Hsu
email: sherry821001[at]gmail[dot]com

rss: rss

plugins:
  - jekyll-feed
  - jekyll-sitemap
  
header_pages:
  - Sherry.md
 
